"""onboarding and legal consent

Revision ID: 2297819147f0
Revises: b87f9d5bda94
Create Date: 2026-07-01 15:03:14.427618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2297819147f0'
down_revision: Union[str, None] = 'b87f9d5bda94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DEFAULT_TERMS = (
    "Términos de uso y aviso de salud de NutriBot\n\n"
    "NutriBot es un asistente informativo de nutrición. La información que ofrece "
    "tiene fines educativos y de orientación general, y NO constituye consejo "
    "médico ni sustituye la consulta con un médico o dietista-nutricionista "
    "colegiado.\n\n"
    "Al aceptar, confirmas que:\n"
    "- Eres mayor de edad.\n"
    "- Entiendes que las recomendaciones son orientativas y que debes consultar a "
    "un profesional sanitario ante cualquier condición médica, embarazo, alergia "
    "grave o duda relevante.\n"
    "- Autorizas el tratamiento de los datos que facilites (peso, altura, objetivos, "
    "registros de comidas) con el fin de ofrecerte el seguimiento nutricional del "
    "servicio.\n\n"
    "Puedes solicitar la eliminación de tus datos en cualquier momento. Este texto "
    "es un valor por defecto y podrá actualizarse."
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.Enum('TERMS', 'PRIVACY', name='legal_doc_type'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_consents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('legal_document_id', sa.BigInteger(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['legal_document_id'], ['legal_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.add_column('nutrition_profiles', sa.Column('target_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('nutrition_profiles', sa.Column('weekly_rate_kg', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('nutrition_profiles', sa.Column('timezone', sa.String(length=64), nullable=False, server_default='Europe/Madrid'))
    op.add_column('nutrition_profiles', sa.Column('reminders_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Seed a default, editable terms document (managed from admin in Phase 8).
    legal_documents = sa.table(
        "legal_documents",
        sa.column("doc_type", sa.Enum("TERMS", "PRIVACY", name="legal_doc_type")),
        sa.column("version", sa.Integer),
        sa.column("content", sa.Text),
        sa.column("is_active", sa.Boolean),
    )
    op.bulk_insert(
        legal_documents,
        [
            {
                "doc_type": "TERMS",
                "version": 1,
                "is_active": True,
                "content": DEFAULT_TERMS,
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed_at')
    op.drop_column('nutrition_profiles', 'reminders_enabled')
    op.drop_column('nutrition_profiles', 'timezone')
    op.drop_column('nutrition_profiles', 'weekly_rate_kg')
    op.drop_column('nutrition_profiles', 'target_weight_kg')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_table('legal_documents')
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS legal_doc_type")
